<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                                    xyz="0 0 0" rpy="${pi / 2} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="steering_length" value="0.1"/>
    <xacro:property name="steering_width" value="0.1"/>
    <xacro:property name="steering_height" value="0.02"/>
    <xacro:property name="small_wheel_radius" value="0.05"/>
    <xacro:property name="small_wheel_length" value="0.02"/>

    <material name="blue">
        <color rgba="0 0 0.5 1" />
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />    
        </collision>
        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${small_wheel_radius}" length="${small_wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${small_wheel_radius}" length="${small_wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${small_wheel_radius}" h="${small_wheel_length}"
                                    xyz="0 0 0" rpy="${pi / 2} 0 0"/>
    </link>

    <link name="base_steering_link">
        <visual>
            <geometry>
                <box size="${steering_length} ${steering_width} ${steering_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${steering_length} ${steering_width} ${steering_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </collision>
        <xacro:box_inertia m="0.5" l="${steering_length}" w="${steering_width}" h="${steering_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-0.15 -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-0.15 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_steering_caster_wheel_joint" type="continuous">
        <parent link="base_steering_link" />
        <child link="caster_wheel_link" />
        <origin xyz="0 0 -0.05" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_steering_joint" type="revolute">
        <parent link="base_link" />
        <child link="base_steering_link" />
        <origin xyz="0.2 0 -0.01" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="${pi/2}" upper="${-pi/2}" effort="1.0" velocity="1.0"/>
    </joint>

</robot>